import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ArrowRightIcon, Sparkles, Brain, Dumbbell } from "lucide-react";
import TerminalOverlay from "./_components/TerminalOverlay";
import UserPrograms from "./_components/UserPrograms";

export default function Home() {
  return (
    <main className="min-h-screen bg-zinc-950 text-gray-100 overflow-hidden flex flex-col">
      <section className="relative px-6 lg:px-20 py-24 flex flex-col lg:flex-row gap-20 items-center">
        <div className="relative w-full max-w-md mx-auto lg:mx-0 flex flex-col gap-4">
          <div className="relative aspect-square rounded-[1.5rem] overflow-hidden border border-blue-700/50 bg-zinc-900/70 backdrop-blur-md shadow-xl shadow-blue-900/40 group transition-all duration-300 group-hover:scale-[1.01] group-hover:shadow-purple-700/40">
            <div className="absolute -inset-4 rounded-[2rem] border-4 border-purple-600/50 shadow-2xl shadow-blue-800/40 animate-pulse-border pointer-events-none z-0" />

            <img
              src="https://media.licdn.com/dms/image/v2/D5612AQEiADotL0DRgw/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1689665628812?e=2147483647&v=beta&t=8VJ1MBpT_TGtbGY6lUuVn4rcnyQG4DaYpsRhJHlEWXo"
              alt="AI Fitness Coach"
              className="w-full h-full object-cover opacity-80 z-10"
            />

            <div className="absolute inset-0 bg-gradient-to-t from-zinc-950 via-zinc-950/40 to-transparent z-20" />
            <div className="absolute inset-0 bg-[linear-gradient(transparent_0%,transparent_calc(50%-1px),rgba(59,130,246,0.6)_50%,transparent_calc(50%+1px),transparent_100%)] bg-[length:100%_8px] animate-scanline pointer-events-none z-20" />

            <div className="absolute top-1/2 left-1/2 w-1/2 h-1/2 border-2 border-purple-500/60 rounded-full animate-pulse-slow -translate-x-1/2 -translate-y-1/2 z-20 pointer-events-none" />
            <div className="absolute inset-0 pointer-events-none z-20">
              <div className="absolute top-1/2 left-0 w-1/4 h-1 bg-blue-500/70 rounded-full"></div>
              <div className="absolute top-1/2 right-0 w-1/4 h-1 bg-purple-500/70 rounded-full"></div>
              <div className="absolute top-0 left-1/2 h-1/4 w-1 bg-blue-500/70 rounded-full"></div>
              <div className="absolute bottom-0 left-1/2 h-1/4 w-1 bg-purple-500/70 rounded-full"></div>
            </div>
          </div>

          <TerminalOverlay />
        </div>

        <div className="flex-1 space-y-10 text-center lg:text-left">
          <h1 className="text-5xl md:text-6xl font-extrabold leading-tight tracking-tight drop-shadow-md">
            <span className="text-blue-400">Train Smarter</span>{" "}
            <span className="text-gray-50">with</span>{" "}
            <span className="text-purple-400">AI Power</span>
          </h1>

          <p className="text-gray-300 text-lg max-w-xl mx-auto lg:mx-0">
            Get a tailored fitness and nutrition plan generated by our AI.
            Whether you're a beginner or athlete, you'll always train with
            purpose.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 max-w-2xl mx-auto lg:mx-0 pt-6">
            <div className="p-5 border border-purple-700/50 rounded-xl bg-zinc-900/60 shadow-lg hover:shadow-purple-700/40 transition-all">
              <div className="flex items-center gap-3 mb-3 text-purple-400 font-mono text-sm uppercase tracking-wide">
                <Brain className="w-5 h-5" />
                Adaptive AI Engine
              </div>
              <p className="text-gray-300 text-sm">
                Our system adjusts to your lifestyle, limitations, and goals.
              </p>
            </div>

            <div className="p-5 border border-blue-700/50 rounded-xl bg-zinc-900/60 shadow-lg hover:shadow-blue-700/40 transition-all">
              <div className="flex items-center gap-3 mb-3 text-blue-400 font-mono text-sm uppercase tracking-wide">
                <Dumbbell className="w-5 h-5" />
                Dynamic Workout Plans
              </div>
              <p className="text-gray-300 text-sm">
                Unique strength, cardio, and recovery plans generated for you.
              </p>
            </div>
          </div>

          <div className="pt-8">
            <Button
              size="lg"
              asChild
              className="relative overflow-hidden bg-gradient-to-r from-blue-600 to-purple-600 text-white px-10 py-6 text-xl font-bold rounded-xl shadow-lg shadow-blue-800/50 hover:from-blue-700 hover:to-purple-700 transition-all duration-300 ease-in-out group"
            >
              <Link href={"/generate"} className="flex items-center font-mono">
                Generate My Plan
                <ArrowRightIcon className="ml-3 size-6 transition-transform duration-300 group-hover:translate-x-1" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      <div className="h-1 w-full bg-gradient-to-r from-blue-500 via-purple-500 to-blue-500 opacity-80 rounded-full shadow-inner shadow-purple-800/30" />

      <UserPrograms />
    </main>
  );
}
